services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: sportsbuddies
      POSTGRES_PASSWORD: sportsbuddies
      POSTGRES_DB: sportsbuddies
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: